import "./globals.css"
import type { Metadata } from "next"
import { Nunito_Sans } from "next/font/google"

const nunito_sans = Nunito_Sans({
  // weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={nunito_sans.className}>{children}</body>
    </html>
  )
}
